# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""Security-oriented runtime primitives."""

from nooa.security.effects import EffectRecord
from nooa.security.egress import (
    DEFAULT_EFFECT_EGRESS_MAX_FRAME_BYTES,
    DEFAULT_EFFECT_EGRESS_MAX_RECORDS,
    DEFAULT_EFFECT_EGRESS_MAX_TOTAL_BYTES,
    EFFECT_EGRESS_COMPLETENESS_SIGNALS,
    EFFECT_EGRESS_FRAME_KEYS,
    EFFECT_EGRESS_RECORD_EVENT_TYPE,
    EFFECT_EGRESS_RECORD_KEYS,
    EFFECT_EGRESS_SCHEMA_VERSION,
    EFFECT_EGRESS_SCHEMA_VERSION_PATTERN,
    EFFECT_EGRESS_SCHEMA_VERSION_PATTERN_MATCH_MODE,
    EFFECT_EGRESS_SCHEMA_VERSION_V2,
    EFFECT_EGRESS_STREAM_END_EVENT_TYPE,
    EFFECT_EGRESS_STREAM_END_FRAME_KEYS,
    EFFECT_EGRESS_STREAM_END_KEYS,
    EFFECT_EGRESS_SUPPORTED_SCHEMA_VERSIONS,
    MAX_EFFECT_EGRESS_JSON_INTEGER,
    MAX_EFFECT_EGRESS_SEQUENCE,
    EffectEgressCompletenessSignal,
    EffectEgressFrameTooLargeError,
    EffectEgressIncompleteError,
    EffectEgressInputTooLargeError,
    EffectEgressReadResult,
    EffectEgressSchemaVersion,
    EffectEgressSinkClosedError,
    EffectEgressSinkFailedError,
    FdEffectSink,
    UnsupportedEffectEgressVersionError,
    effect_egress_completeness_signals,
    read_effect_egress,
    require_complete_effect_egress,
)
from nooa.security.evidence import (
    DetectorInput,
    ReceiptCoverage,
    detector_input_from_egress,
)
from nooa.security.findings import SecurityFinding
from nooa.security.install import (
    AgentCallEffectObserver,
    EffectObservation,
    EffectObserver,
    install_agent_call_effect_recorder,
    install_effect_recorder,
)
from nooa.security.observers import framework_guard_observer
from nooa.security.receipts import (
    RECEIPT_SCOPE_SIGNALS,
    ReceiptScopeError,
    ReceiptScopeSignal,
    ReceiptScopeValidation,
    SecurityReceipt,
    receipt_scope_signals,
    require_valid_receipt_scope,
    validate_receipt_scope,
)
from nooa.security.sinks import (
    EffectRecordSinkBackend,
    EffectSink,
    JsonlEffectSink,
    install_effect_sink,
)

__all__ = [
    "DEFAULT_EFFECT_EGRESS_MAX_FRAME_BYTES",
    "DEFAULT_EFFECT_EGRESS_MAX_RECORDS",
    "DEFAULT_EFFECT_EGRESS_MAX_TOTAL_BYTES",
    "EFFECT_EGRESS_COMPLETENESS_SIGNALS",
    "EFFECT_EGRESS_FRAME_KEYS",
    "EFFECT_EGRESS_RECORD_EVENT_TYPE",
    "EFFECT_EGRESS_RECORD_KEYS",
    "EFFECT_EGRESS_SCHEMA_VERSION",
    "EFFECT_EGRESS_SCHEMA_VERSION_V2",
    "EFFECT_EGRESS_SCHEMA_VERSION_PATTERN",
    "EFFECT_EGRESS_SCHEMA_VERSION_PATTERN_MATCH_MODE",
    "EFFECT_EGRESS_STREAM_END_EVENT_TYPE",
    "EFFECT_EGRESS_STREAM_END_FRAME_KEYS",
    "EFFECT_EGRESS_STREAM_END_KEYS",
    "EFFECT_EGRESS_SUPPORTED_SCHEMA_VERSIONS",
    "MAX_EFFECT_EGRESS_JSON_INTEGER",
    "MAX_EFFECT_EGRESS_SEQUENCE",
    "AgentCallEffectObserver",
    "DetectorInput",
    "EffectEgressCompletenessSignal",
    "EffectEgressFrameTooLargeError",
    "EffectEgressIncompleteError",
    "EffectEgressInputTooLargeError",
    "EffectEgressReadResult",
    "EffectEgressSchemaVersion",
    "EffectEgressSinkClosedError",
    "EffectEgressSinkFailedError",
    "EffectObservation",
    "EffectObserver",
    "EffectRecord",
    "EffectRecordSinkBackend",
    "EffectSink",
    "FdEffectSink",
    "JsonlEffectSink",
    "RECEIPT_SCOPE_SIGNALS",
    "ReceiptCoverage",
    "ReceiptScopeError",
    "ReceiptScopeSignal",
    "ReceiptScopeValidation",
    "SecurityFinding",
    "SecurityReceipt",
    "UnsupportedEffectEgressVersionError",
    "detector_input_from_egress",
    "effect_egress_completeness_signals",
    "framework_guard_observer",
    "install_agent_call_effect_recorder",
    "install_effect_recorder",
    "install_effect_sink",
    "read_effect_egress",
    "require_complete_effect_egress",
    "receipt_scope_signals",
    "require_valid_receipt_scope",
    "validate_receipt_scope",
]
